//! Orthanc API client generated by [OpenAPI Generator](https://openapi-generator.tech/).

#![allow(
    non_snake_case,
    unused_imports,
    clippy::too_many_arguments,
    clippy::empty_docs
)]

/// API client.
#[cfg(feature = "client")]
pub mod apis;

/// Orthanc OpenAPI request and response models.
pub mod models;
