//! Orthanc plugin bindings generated by [rust-bindgen](https://rust-lang.github.io/rust-bindgen/).

#![allow(
    dead_code,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    clippy::empty_docs,
    clippy::redundant_static_lifetimes,
    clippy::unreadable_literal,
    clippy::cognitive_complexity,
    clippy::useless_transmute,
    improper_ctypes,
    unnecessary_transmutes
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
