# Build plugin and start Orthanc
up *args: build _touch
    podman-compose up {{args}}

# Shut down and delete volumes
down *args:
    podman-compose down -v {{args}}

# Run test script.
test:
    ./test.sh

# Build Rust library
build:
    cargo build --lib

_touch:
    touch ./output.txt
