pub mod api;
#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(non_upper_case_globals)]
#[allow(clippy::redundant_static_lifetimes)]
#[allow(clippy::unreadable_literal)]
#[allow(clippy::cognitive_complexity)]
#[allow(clippy::useless_transmute)]
#[allow(improper_ctypes)]
#[allow(unnecessary_transmutes)]
pub mod bindings;

/// Orthanc Rest API models generated by OpenAPI-generator.
#[allow(non_snake_case)]
#[allow(unused)]
pub mod models;

pub(crate) mod callback;
mod helpers;
pub(crate) mod http;
mod on_change;
mod resource_id;
pub use on_change::{OnChangeEvent, OnChangeThread};
